#!/bin/bash

echo "# begin build properties"
echo "# autogenerated by buildinfo.sh"

echo "ro.build.id=$BUILD_ID"
echo "ro.build.display.id=$BUILD_DISPLAY_ID"
echo "ro.build.version.incremental=$BUILD_NUMBER"
echo "ro.build.version.sdk=$PLATFORM_SDK_VERSION"
echo "ro.build.version.codename=$PLATFORM_VERSION_CODENAME"
echo "ro.build.version.release=$PLATFORM_VERSION"
echo "ro.build.date=`date`"
echo "ro.build.date.utc=`date +%s`"
echo "ro.build.type=$TARGET_BUILD_TYPE"
echo "ro.build.user=$USER"
echo "ro.build.host=`hostname`"
echo "ro.build.tags=$BUILD_VERSION_TAGS"
echo "ro.product.model=$PRODUCT_MODEL"
echo "ro.product.brand=$PRODUCT_BRAND"
echo "ro.product.name=$PRODUCT_NAME"
echo "ro.product.device=$TARGET_DEVICE"
echo "ro.product.board=$TARGET_BOOTLOADER_BOARD_NAME"
echo "ro.product.cpu.abi=$TARGET_CPU_ABI"
if [ -n "$TARGET_CPU_ABI2" ] ; then
  echo "ro.product.cpu.abi2=$TARGET_CPU_ABI2"
fi
echo "ro.product.manufacturer=$PRODUCT_MANUFACTURER"
if [ -n "$PRODUCT_DEFAULT_LANGUAGE" ] ; then
  echo "ro.product.locale.language=$PRODUCT_DEFAULT_LANGUAGE"
fi
if [ -n "$PRODUCT_DEFAULT_REGION" ] ; then
  echo "ro.product.locale.region=$PRODUCT_DEFAULT_REGION"
fi
echo "ro.wifi.channels=$PRODUCT_DEFAULT_WIFI_CHANNELS"
echo "ro.board.platform=$TARGET_BOARD_PLATFORM"

echo "# ro.build.product is obsolete; use ro.product.device"
echo "ro.build.product=$TARGET_DEVICE"

echo "# Do not try to parse ro.build.description or .fingerprint"
echo "ro.build.description=$PRIVATE_BUILD_DESC"
echo "ro.build.fingerprint=$BUILD_FINGERPRINT"
echo "ro.build.characteristics=$TARGET_AAPT_CHARACTERISTICS"

echo "ro.carbon.device=$MINIONS_DEVICE"

echo "# end build properties"

echo "#Mgbotoe Minions Edit"

echo "#Better Scrolling"
echo "windowsmgr.max_events_per_sec=300"
echo "ro.max.fling_velocity=12000"
echo "ro.min.fling_velocity=8000"

echo "#Better Battery"
echo "ro.ril.disable.power.collapse=1"
echo "wifi.supplicant_scan_interval=200"
echo "windowsmgr.max_events_per_sec=60"
echo "persist.sys.purgeable_assets=1"
echo "ro.config.hw_fast_dormancy=1"
echo "ro.config.hw_power_saving=1"
echo "pm.sleep_mode=1" 

echo "#Dalvik VM Tweaks"
echo "dalvik.vm.startheapsize=8M"
echo "dalvik.vm.dexopt-flags=m=y"
echo "dalvik.vm.execution-mode=init:jit"
echo "ro.kernel.android.checkjni=0"
echo "ro.kernel.checkjni=0" 

echo "#Error Disabled" 
echo "profiler.force_disable_err_rpt=1"
echo "profiler.force_disable_ulog=1"
echo "ro.kernel.android.checkjni=0"
echo "ro.kernel.checkjni=0"

echo "#Disable Blackscreen"
echo "ro.lge.proximity.delay=25"
echo "mot.proximity.delay=25"

echo "#launcher"
echo "ro.HOME_APP_ADJ = 1"